FROM debian:latest

WORKDIR /usr/src/
COPY ./inquisitor.py .
COPY sshd_config /etc/ssh/sshd_config

RUN echo "root:root" | chpasswd
RUN apt-get update -y && apt upgrade -y
RUN apt-get install openssh-server net-tools iputils-ping -y
RUN apt-get install vim python3 python3-pip python3-dev libpcap-dev -y
RUN pip3 install scapy pcapy argparse requests 
ENTRYPOINT cd /usr/src/
ENTRYPOINT service ssh start; tail -f /dev/null
EXPOSE 8484
